
version: '3'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  app:
    # image: marsonic/hollapi
    build: .
    container_name: app
    ports:
      - 5000:8080
    environment:
      API_KEY: ${API_KEY}
      PASSWORD_FOR_ROUTE: ${PASSWORD_FOR_ROUTE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:


#   nginx:
#     image: nginx
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/letsencrypt:/etc/letsencrypt
#     depends_on:
#       - app
#     networks:
#       - web
# networks:
#   web:
#     driver: bridge


  # db:
  #   container_name: postgres
  #   image: postgres
  #   ports:
  #     - '5433:${DB_PORT}'
  #   volumes:
  #     - ./sql-scripts:/docker-entrypoint-initdb.d/
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}


  # app:
  #   build: .
  #   ports:
  #     - ${PORT}:${PORT}
  #   restart: always
  #   #DB_HOST: postgres
  #   #DB_NAME: hollywood
  #   #DB_USER: vova
  #   # this needs to be the container port on which the db runs (the right most number under ports in the postgres service)
  #   # i.e. we need to specify container port and not the host port
  #   #DB_PORT: 5432
  #   # depends_on:
  #   #   - db
  #   volumes:
  #   - .:/usr/src/app



# volumes: 
#   data: {}


